version: '3.8'

services:
  redis:
    image: redis:7.4
    container_name: redis_server
    restart: always
    ports:
      - "6380:6379"
  
  app:
    build:
      context: ./web_crawling
    container_name: web_crawling_app
    depends_on:
      - redis
    environment:
      CHROME_DIR: /usr/bin/google-chrome-stable
      REDIS_HOST: redis_server
      REDIS_PORT: 6379
